### ISSUE TITLE
gnd_pid / pid

### ISSUE THREAD

**Issue by pronguen** [rero/rero-mef#32]
The JSON instance of a MEF GND person has two properties for the same identifiers:
* `gnd_pid`
* `pid`

`gnd_pid` is not in the [JSON schema](https://github.com/rero/rero-mef/blob/master/rero_mef/authorities/jsonschemas/authorities/gnd-person-v0.0.1.json).

The same problem applies to BNF, RERO and VIAF persons.

The model should be simplified in order to have only one `pid` property used for persons from any sources.

**Comment by iGormilhit** [comment]
5946d529dcca2bb2922df728e05994950e9e2a44 closes it.
